name: Buid_KSU

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: true
        default: 'true'

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Setup kernel source
      run: |
        echo "Free space:"
        df -h
        cd $GITHUB_WORKSPACE
        mkdir -p ~/.bin
        PATH="${HOME}/.bin:${PATH}"
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
        chmod a+rx ~/.bin/repo
        mkdir android-kernel && cd android-kernel
        repo init --depth=1 --u https://android.googlesource.com/kernel/manifest -b common-android12-5.10-lts
        repo sync -c -j1
        df -h

    - name: Setup KernelSU
      run: |
        cd $GITHUB_WORKSPACE/android-kernel
        echo "[+] KernelSU setup"
        GKI_ROOT=$(pwd)
        echo "[+] GKI_ROOT: $GKI_ROOT"
        echo "[+] Copy KernelSU driver to $GKI_ROOT/common/drivers"
        git clone --depth=1 https://github.com/hubbylei/KernelSU -b main
        ln -sf $GITHUB_WORKSPACE/KernelSU/kernel $GKI_ROOT/common/drivers/kernelsu
        echo "[+] Add KernelSU driver to Makefile"
        DRIVER_MAKEFILE=$GKI_ROOT/common/drivers/Makefile
        grep -q "kernelsu" $DRIVER_MAKEFILE || echo "obj-y += kernelsu/" >> $DRIVER_MAKEFILE
        echo "[+] Apply KernelSU patches"
        cd $GKI_ROOT/common/ && git apply $GITHUB_WORKSPACE/KernelSU/.github/patches/$PATCH_PATH/*.patch || echo "[-] No patch found"
        echo "[+] KernelSU setup done."

    - name: Make working directory clean to avoid dirty
      run: |
        cd $GITHUB_WORKSPACE/android-kernel
        git config --global user.email "hubbylei@hubbylei.dynu.net"
        git config --global user.name "hubbylei"
        cd common/ && git add -A && git commit -a -m "Add KernelSU"
        repo status
        rm -rf .repo

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@main
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')

    - name: Build boot.img
      run: |
        cd $GITHUB_WORKSPACE/android-kernel
        LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh

    - name: Prepare artifacts
      id: prepareArtifacts
      run: |
        mkdir output
        cp android-kernel/out/*/dist/Image ./output/
        git clone https://github.com/Kernel-SU/AnyKernel3
        rm -rf ./AnyKernel3/.git
        cp android-kernel/out/*/dist/Image ./AnyKernel3/

    - name: Upload Image
      uses: actions/upload-artifact@v4
      with:
       name: Image
       path: ./output/*

    - name: Upload AnyKernel3
      uses: actions/upload-artifact@v4
      with:
        name: AnyKernel3-android12-5.10.209
        path: ./AnyKernel3/*
