name: Buid_KSU

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: true
        default: 'false'

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Setup kernel source
      run: |
        echo "Free space:"
        df -h
        cd $GITHUB_WORKSPACE
        mkdir -p ${HOME}/bin
        PATH="${HOME}/bin:${PATH}"
        curl https://storage.googleapis.com/git-repo-downloads/repo > ${HOME}/bin/repo
        chmod a+rx ${HOME}/bin/repo
        git config --global user.email "hubbylei@hubbylei.dynu.net"
        git config --global user.name "hubbylei"
        mkdir android-kernel && cd android-kernel
        repo init --depth=1 --u https://android.googlesource.com/kernel/manifest -b common-android12-5.10-lts
        repo sync -c -j1

    - name: Setup KernelSU
      run: |
        PATH="${HOME}/bin:${PATH}"
        cd $GITHUB_WORKSPACE/android-kernel
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@main
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')

    - name: Build Image
      id: build
      run: |
        PATH="${HOME}/bin:${PATH}"
        cd $GITHUB_WORKSPACE/android-kernel/common
        repo status
        git add -A && git commit -a -m "Add KernelSU"
        VERSION=$(grep "^VERSION = .*$" Makefile | awk '{print $3}')
        PATCHLEVEL=$(grep "^PATCHLEVEL = .*$" Makefile | awk '{print $3}')
        SUBLEVEL=$(grep "^SUBLEVEL = .*$" Makefile | awk '{print $3}')
        echo "kernel_ver="${VERSION}.${PATCHLEVEL}.${SUBLEVEL}"" >> $GITHUB_OUTPUT
        rm -rf $GITHUB_WORKSPACE/.repo
        cd $GITHUB_WORKSPACE/android-kernel
        LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh
        df -h

    - name: Prepare artifacts
      id: prepareArtifacts
      run: |
        mkdir output
        cp android-kernel/out/*/dist/Image ./output/
        git clone https://github.com/Kernel-SU/AnyKernel3
        rm -rf ./AnyKernel3/.git
        cp android-kernel/out/*/dist/Image ./AnyKernel3/

    - name: Upload Image
      uses: actions/upload-artifact@v4
      with:
       name: Image
       path: ./output/*

    - name: Upload AnyKernel3
      uses: actions/upload-artifact@v4
      with:
        name: AnyKernel3-android12-${{ steps.build.outputs.kernel_ver }}
        path: ./AnyKernel3/*
