name: Update Checker

on:
  workflow_dispatch:
  schedule:
    - cron: 0 * * * *

env:
  TZ: Asia/Shanghai

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
    - name: Get Version
      id: getver
      run: |
        git clone --depth 1 https://android.googlesource.com/kernel/common -b android12-5.10-lts
        cd common
        VERSION=$(grep "^VERSION = .*$" Makefile | awk '{print $3}')
        PATCHLEVEL=$(grep "^PATCHLEVEL = .*$" Makefile | awk '{print $3}')
        SUBLEVEL=$(grep "^SUBLEVEL = .*$" Makefile | awk '{print $3}')
        Kernel_VER="android12-${VERSION}.${PATCHLEVEL}.${SUBLEVEL}"
        echo "Kernel_VER=$Kernel_VER" >> "$GITHUB_OUTPUT"

    - name: Get Cache Version
      id: getcache
      uses: actions/cache@v4
      with:
        path: .commitHash
        key: ${{ steps.getver.outputs.Kernel_VER }}

    - name: Save New Version
      if: steps.getcache.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.getver.outputs.Kernel_VER }} | tee .commitHash

    - name: Auto compile
      if: steps.getcache.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v3
      with:
        event-type: Auto compile

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 10
