name: Update Checker

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

env:
  TZ: Asia/Shanghai

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
    - name: Get Commit Version
      id: getVersion
      run: |
        git clone https://github.com/tiann/KernelSU -b main
        cd KernelSU
        echo "KSU_VER=$(($(git rev-list --count HEAD) + 10200))" >> "$GITHUB_OUTPUT"

    - name: Compare Commit Version
      id: cacheVersion
      uses: actions/cache@v4
      with:
        path: .KSU_VER
        key: KSU_VER-${{ steps.getVersion.outputs.KSU_VER }}

    - name: Save New Commit Version
      if: steps.cacheVersion.outputs.cache-hit != 'true'
      run: |
        echo ${{ steps.getVersion.outputs.KSU_VER }} | tee .KSU_VER

    - name: Trigger build
      if: steps.cacheVersion.outputs.cache-hit != 'true'
      uses: peter-evans/repository-dispatch@v3
      with:
        event-type: Auto compile

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 1
